language: cpp

compiler:
    - gcc

before_install:
    - sudo add-apt-repository -y ppa:team-xbmc/ppa
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq

install:
    - sudo apt-get install -qq libsdl2-dev libfreetype6-dev gcc-4.8 g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

before_script:
     - cmake .

script: make && ctest -VV
